"""Add GivingCategory and Donation models

Revision ID: 2101d617fb35
Revises: ca4de292f6eb
Create Date: 2026-04-02 13:51:01.663971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2101d617fb35'
down_revision = 'ca4de292f6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giving_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('giving_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_giving_categories_slug'), ['slug'], unique=True)

    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('donor_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mpesa_checkout_id', sa.String(length=100), nullable=True),
    sa.Column('callback_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['giving_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_mpesa_checkout_id'), ['mpesa_checkout_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_status'))
        batch_op.drop_index(batch_op.f('ix_donations_mpesa_checkout_id'))

    op.drop_table('donations')
    with op.batch_alter_table('giving_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_giving_categories_slug'))

    op.drop_table('giving_categories')
    # ### end Alembic commands ###
