"""Add Ministry, Fellowship, ConnectionCard, VolunteerSignup models

Revision ID: 9fdb95ac4a04
Revises: 92ad18ab5889
Create Date: 2026-04-02 03:11:31.766430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdb95ac4a04'
down_revision = '92ad18ab5889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('how_heard', sa.String(length=100), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('prayer_needs', sa.Text(), nullable=True),
    sa.Column('is_first_visit', sa.Boolean(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fellowships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_day', sa.String(length=20), nullable=True),
    sa.Column('meeting_time', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fellowships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fellowships_slug'), ['slug'], unique=True)

    op.create_table('ministries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ministries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ministries_slug'), ['slug'], unique=True)

    op.create_table('ministry_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_team_members_ministry_id', 'ministries', ['ministry_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_members_ministry_id', type_='foreignkey')

    op.drop_table('volunteer_signups')
    op.drop_table('ministry_content')
    with op.batch_alter_table('ministries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ministries_slug'))

    op.drop_table('ministries')
    with op.batch_alter_table('fellowships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fellowships_slug'))

    op.drop_table('fellowships')
    op.drop_table('connection_cards')
    # ### end Alembic commands ###
