"""Add Sermon and MediaItem models

Revision ID: ca4de292f6eb
Revises: 9fdb95ac4a04
Create Date: 2026-04-02 13:10:02.882383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4de292f6eb'
down_revision = '9fdb95ac4a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_media_type'), ['media_type'], unique=False)

    op.create_table('sermons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('speaker', sa.String(length=100), nullable=True),
    sa.Column('series', sa.String(length=100), nullable=True),
    sa.Column('scripture_reference', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=True),
    sa.Column('sermon_date', sa.Date(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sermons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sermons_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sermons_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sermons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sermons_slug'))
        batch_op.drop_index(batch_op.f('ix_sermons_content_type'))

    op.drop_table('sermons')
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_items_media_type'))
        batch_op.drop_index(batch_op.f('ix_media_items_category'))

    op.drop_table('media_items')
    # ### end Alembic commands ###
